CREATE TABLE Samochody_EXCEL (
    SAMOCHOD_ID INT PRIMARY KEY,
    MARKA VARCHAR(50),
    MODEL_SAMOCHODU VARCHAR(50),
    ROK_PRODUKCJI INT,
    NR_REJESTRACYJNY VARCHAR(20),
    TYP_ID INT,
    KOLOR VARCHAR(20),
    PRZEBIEG INT,
    POJEMNOSC_SILNIKA INT,
    STAN_PALIWA INT,
    CENA_ZA_DZIEN DECIMAL(10, 2),
    LICZBA_MIEJSCA INT,
    STATUS INT,
    FOREIGN KEY (TYP_ID) REFERENCES Typy_samochodow(TYP_ID)
);


CREATE PROCEDURE DodajSamochod
@SAMOCHOD_ID INT,
@MARKA NVARCHAR(255),
@MODEL_SAMOCHODU NVARCHAR(255),
@ROK_PRODUKCJI INT,
@NR_REJESTRACYJNY NVARCHAR(255),
@TYP_ID INT,
@KOLOR NVARCHAR(255),
@PRZEBIEG INT,
@POJEMNOSC_SILNIKA INT,
@STAN_PALIWA INT,
@CENA_ZA_DZIEN DECIMAL(10, 2),
@LICZBA_MIEJSCA INT,
@STATUS INT
AS
BEGIN
INSERT INTO Samochody_EXCEL (
SAMOCHOD_ID,
MARKA,
MODEL_SAMOCHODU,
ROK_PRODUKCJI,
NR_REJESTRACYJNY,
TYP_ID,
KOLOR,
PRZEBIEG,
POJEMNOSC_SILNIKA,
STAN_PALIWA,
CENA_ZA_DZIEN,
LICZBA_MIEJSCA,
STATUS
) VALUES (
@SAMOCHOD_ID,
@MARKA,
@MODEL_SAMOCHODU,
@ROK_PRODUKCJI,
@NR_REJESTRACYJNY,
@TYP_ID,
@KOLOR,
@PRZEBIEG,
@POJEMNOSC_SILNIKA,
@STAN_PALIWA,
@CENA_ZA_DZIEN,
@LICZBA_MIEJSCA,
@STATUS
);
END;

EXEC DodajSamochod
    1,
    'Toyota',
    'Corolla',
    2020,
    'ABC1234',
    1,
    'Czerwony',
    15000,
    1800,
    50,
    100.00,
    5,
    0;

